version: "3.9"
services:
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - "./database/storage:/var/lib/mysql"
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment: 
      MYSQL_ROOT_PASSWORD: root
    container_name: "db"
    expose:
      - 3306
    ports:
      - "3306:3306"

  adminer:
    image: "adminer:latest"
    ports:
      - "8000:8080"
    depends_on:
      - "db"
    links:
      - "db"

  backend:
    build: ./backend 
    ports:
      - "5050:5050"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    ports:
      - "80:8080"